name: Build and Deploy CV
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use the latest available Python version

      - name: Install dependencies
        run: |
          pip install weasyprint
          pip install --no-cache-dir -r requirements.txt

      - name: Generate PDF from HTML
        run: python generate.py  # Run your script to generate the PDF

      - name: Move PDFs to _site directory
        run: |
          mkdir -p _site  # Ensure the _site directory exists
          find . -name '*.pdf' -exec sh -c 'mkdir -p "_site/$(dirname "{}")" && mv "{}" "_site/{}"' \;  # Move all PDFs while preserving directory structure

      - name: Move HTML files and CNAME recursively
        run: |
          mkdir -p _site  # Ensure the _site directory exists
          find . -name '*.html' -exec sh -c 'mkdir -p "_site/$(dirname "{}")" && mv "{}" "_site/{}"' \; || true  # Move all HTML files while preserving directory structure
          mv CNAME _site/ || true  # Move the CNAME file to _site directory
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
