name: Build and Deploy CV
on:
  push:
    branches: ["main"]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'  # Use the latest available Python version

      - name: Install dependencies
        run: |
          pip install weasyprint
          pip install --no-cache-dir -r requirements.txt

      - name: Generate PDF from HTML
        run: python generate.py  # Run your script to generate the PDF

      - name: Move PDF
        run: |
          mkdir -p _site
          mv resume.pdf ./_site/  # Move the generated PDF to _site directory

      - name: Copy index.html and CNAME
        run: |
          cp index.html _site/ || true
          cp CNAME _site/ || true
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
